version: 2

settings: &settings
    working_directory: ~/spt-boost
    docker:
        - image: circleci/openjdk:8-jdk

jobs:
    build:
        <<: *settings
        steps:
            - checkout:
                path: ~/spt-boost
            - run: |
                curl -fsSL https://git.io/vpRJr | bash -s -- /usr/local/bin
            - restore_cache:
                keys:
                    - cache-{{ .Branch }}
            - run: |
                mvn-settings sonatype ${MAVEN_USERNAME} ${MAVEN_PASSWORD}
            - run: |
                mvn-go-offline
            - save_cache:
                paths:
                    - ~/.m2
                key: cache-{{ .Branch }}
            - run: |
                mvn-license-format
            - run: |
                git-push-all 'Update license headers [ci skip]' || true
            - run: |
                mvn-test
            - run: |
                git-config-user "${GIT_USERNAME}" ${GIT_EMAIL}
            - run: |
                curl -fsSL https://git.io/vpDIq | \
                    bash -s -- https://git.io/vpDY5 ${OPENSSL_PASSWORD}
            - run: |
                curl -fsSL https://git.io/vpDY9 | \
                    bash -s -- ${CIRCLE_BRANCH} ${GPG_PASSWORD} ${VERSION:-}
